# Generated by Django 4.2.10 on 2024-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[(0, 'Iniciante'), (1, 'Intermediário'), (2, 'Avançado')], max_length=15)),
                ('carga_horaria', models.IntegerField()),
                ('data', models.DateTimeField(help_text='aaaa/mm/dd')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
